/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _MAIN_H_RPCGEN
#define _MAIN_H_RPCGEN

#include <rpc/rpc.h>
#include <stdio.h>
#include <time.h>

// define the number of msgs possible to store on server
#define MSG_LIMIT 15

#ifdef __cplusplus
extern "C" {
#endif


// client data contains the client id and a message to store
struct client_data {
	int id;
	char message[8000];
};

typedef struct client_data client_data;

#define DISPLAY_PRG 0x20000101
#define DISPLAY_VER 1

#if defined(__STDC__) || defined(__cplusplus)
#define get 1
extern  int * get_1(int *, CLIENT *);
extern  int * get_1_svc(int *, struct svc_req *);
#define put 2
extern  int * put_1(struct client_data *, CLIENT *);
extern  int * put_1_svc(struct client_data *, struct svc_req *);
extern int display_prg_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define get 1
extern  int * get_1();
extern  int * get_1_svc();
#define put 2
extern  int * put_1();
extern  int * put_1_svc();
extern int display_prg_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_client_data (XDR *, client_data*);

#else /* K&R C */
extern bool_t xdr_client_data ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif



#endif /* !_MAIN_H_RPCGEN */
